# Generated by Django 2.1.5 on 2019-06-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='content',
            field=models.TextField(default='just testing content for rate model, confliction with views.save_rate', null=True),
        ),
    ]
