# Generated by Django 2.1.7 on 2019-05-30 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='rate',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='anonymous', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.TextField(null=True),
        ),
    ]
