# Generated by Django 2.1.7 on 2019-05-30 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190530_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
