# Generated by Django 2.1.5 on 2019-06-07 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190607_2017'),
        ('catalog', '0002_profile_user'),
    ]

    operations = [
    ]
