# Generated by Django 2.1.5 on 2019-05-30 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
