# Generated by Django 2.1.7 on 2019-05-30 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_rate_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='content',
            new_name='texts',
        ),
        migrations.RenameField(
            model_name='rate',
            old_name='content',
            new_name='review',
        ),
    ]
