# Generated by Django 2.1.7 on 2019-06-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_merge_20190607_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates2',
            name='active',
            field=models.IntegerField(default=0),
        ),
    ]
