# Generated by Django 2.1.7 on 2019-06-10 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_profile_profile_pic'),
        ('catalog', '0004_candidates2_active'),
    ]

    operations = [
    ]
