# Generated by Django 2.1.5 on 2019-06-03 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20190530_2212'),
        ('catalog', '0005_auto_20190530_2212'),
    ]

    operations = [
    ]
