# Generated by Django 2.1.7 on 2019-06-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_merge_20190610_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.IntegerField()),
                ('following', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='candidates2',
            name='active',
        ),
    ]
